[FAQs]
    [FAQs.F01]
        Question = "ချေးငွေကို သတ်မှတ်ရက်ထက်စောပြီး ပြန်ပေးလို့ရပါသလား။"
        Answer = "ရပါသည်။ ချေးငွေကို သတ်မှတ်ရက်ထက်စောပြီး ပြန်ပေးခြင်းအတွက် မည်သည့်အခကြေးငွေမှ ပေးရန်မလိုအပ်ပါ။"

    [FAQs.F02]
        Question = "ချေးငွေ (ငွေ) ကို ဘယ်လိုလက်ခံရရှိမှာလဲ။"
        Answer = "သင့်ကိုယ်ပိုင်ဘဏ်စာရင်းထဲသို့ တိုက်ရိုက်လွဲပြောင်းပေးမှာ ဖြစ်ပါတယ်။"

    [FAQs.F03]
        Question = "ချေးငွေကို ဘယ်နေရာတွေအတွက် အသုံးပြုလို့ရပါသလဲ။"
        Answer = "အရေးပေါ်ကျန်းမာရေးအသုံးစရိတ်များ၊ ကုန်ပစ္စည်းများဝယ်ယူရန်၊ အတိုးနှုန်းမြင့်မားသည့် ချေးငွေများပြန်လည်ပေးဆပ်ရန်၊ အိမ်ပြင်ရန်နှင့် အခြားအသုံးစရိတ်များစွာအတွက် အသုံးပြုနိုင်ပါသည်။"

    [FAQs.F04]
        Question = "ချေးငွေကို ဘယ်လိုပြန်ပေးရပါမလဲ။"
        Answer = "Mobile App မှတဆင့် MPU Card ဖြင့် လုံခြုံစိတ်ချစွာ တိုက်ရိုက်ပေးချေနိုင်ပါသည်။ ထို့အပြင် Online banking နှင့် Internet banking တို့မှလဲ ငွေလွှဲပေးနိုင်သလို  Ok Dollar, Wave Money အကောင့်များရှိပါကလည်း  ထိုအကောင့်များမှတဆင့် လစဉ်ငွေပေးသွင်းခြင်းကို ပြုလုပ်နိုင်ပါသည်။"

    [FAQs.F05]
        Question = "ချေးငွေလျောက်ထားခြင်းကို ဘယ်လောက်မြန်မြန်လုပ်ဆောင်လို့ ရပါသလဲ။"
        Answer = "လိုအပ်သည့်စာရွက်စာတမ်းများပြည့်စုံပါက Mobile App တွင် လျှောက်လွှာဖြည့်စွက်ခြင်းမှာ (၁၅) မိနစ်ခန့်သာ ကြာမြင့်ပါသည်။"

    [FAQs.F06]
        Question = "ငွေကို ဘယ်အချိန်မှာ လက်ခံရရှိပါမလဲ။"
        Answer = "ချေးငွေလျှောက်လွှာကို လက်ခံအတည်ပြုပြီး (၁) ရက်မှ (၃) ရက်အတွင်း ငွေကိုလက်ခံရရှိမှာ ဖြစ်ပါတယ်။"

    [FAQs.F07]
        Question = "ချေးငွေကို လက်ခံအတည်ပြုပေးရန် ဘယ်လောက်ကြာပါသလဲ။"
        Answer = "လိုအပ်သောစာရွက်စာတမ်း အချက်အလက်များအားလုံးဖြည့်စွက်ပြီး (၄၈) နာရီအတွင်း ချေးငွေလက်ခံအတည်ပြုသည့် ဆုံးဖြတ်ချက်ကို သိရှိနိုင်ပါသည်။"

    [FAQs.F08]
        Question = "ချေးငွေပေါ်တွင် ကောက်ခံသော အခကြေးငွေများ ရှိပါသလား။ ဘယ်လို တွက်ချက်ကောက်ခံပါသလဲ။"
        Answer = "ကြိုတင်ပေးဆပ်ငွေအပေါ်ကောက်ခံခြင်း\nချေးငွေကို သတ်မှတ်ရက်မတိုင်ခင် ကြိုတင်ပေးဆပ်ခြင်းအတွက် မည်သည့်အခကြေးငွေမှ မကောက်ခံပါ။\n\nဝန်ဆောင်ခ\n“စတင်ဆောင်ရွက်ခ” သို့မဟုတ် “ကြိုတင်ပေးရသောငွေကြေးဝန်ဆောင်ခ” ဟုလည်းခေါ်ပါသည်။ တစ်ကြိမ်သာပေးရသော ဝန်ဆောင်ခဖြစ်ပြီးပြန်မအမ်းပါ။ ချေးငွေရယူရန်လုပ်ငန်းစဉ်များအတွက် ဝန်ဆောင်ခဖြစ်ပြီး သင့်ထံသို့ချေးငွေမပေးအပ်ခင် ကြိုတင်နှုတ်ယူထားမည်ဖြစ်ပါသည်။ ဆိုလိုသည်မှာ သင်ရရှိမည့်ချေးငွေပမာဏမှာ သင်လျှောက်ထားသည့်ချေးငွေပမာဏမှ စတင်ဆောင်ရွက်ခကိုယူပြီး ပမာဏဖြစ်သည်။ စတင်ဆောင်ရွက်ခကို သင်ချေးယူသောချေးငွေပမာဏ၏ ရာခိုင်နှုန်းဖြင့် တွက်ချက်ပါသည် (သင့်ပြန်လည်ပေးဆပ်နိုင်မှုပေါ်မူတည်၍ ၁% မှ ၅% ကြားကျသင့်ပါမည်)။\n\nနောက်ကျကြေး\nချေးငွေပြန်ဆပ်ရမည့်နေ့တွင်ပြန်မဆပ်ပါက ဒဏ်ကြေး ၁၅,၀၀၀ ပေးဆောင်ရပါမည်။ လစဉ်ပေးဆပ်ရမည့်ငွေပမာဏကို သတ်မှတ်ရက်ထက်ကျော်လွန်ပြီး အပြည့်အဝပေးဆပ်ခြင်းမရှိပါက ပြန်မဆပ်သေးတဲ့ ၃ ရက်တိုင်း ၁၅,၀၀၀ ကျပ် ထပ်ပေးရပါမည်။  နောက်ကျကြေးကို နောက်ကျသောလအတွက်တစ်ကြိမ်သာကာက်ခံပါမည်။ နောက်ကျကြေးတစ်ကြိမ်ပေးသွင်းရပြီးနောက်ပိုင်းတွင် ပုံမှန်အတိုင်း လစဉ်ပေးဆပ်ရမည့်ငွေကို ဆက်လက်ပေးသွင်းသွားပါက သင့်ချေးငွေသည် ဆက်လက်အသက်ဝင်နေမည် ဖြစ်သော်လည်း ထိုနောက်ကျသောလအတွက် ငွေရင်းပေးဆပ်မှုမှာလျော့နည်းသွားမည်ဖြစ်သည်။ ထို့ကြောင့် ကျန်ရှိသောလများအတွက် အတိုးပမာဏမှာ ပိုမိုလာနိုင်ပြီး နောက်ဆုံးပေးသွင်းရငွေမှာလည်း တိုးလာနိုင်ပါသည်။ အချိန်တစ်ခုခုဖြတ်သန်းပြီးလျှင်နောက်ကျကြေးနဲ့ပတ်သတ်သောကုမ္ပဏီ၏မူဝါဒပြန်လည်ခွင့်ရှိသည်ဟုနားလည်ရပါမည်။ ချေးငွေစာချုပ်သည်လျှင်နောက်ဆုံးအခိုင်အမာဆုံးမူဝါဒဖြစ်ပါသည်။ ပြန်ဆပ်ငွေ မလုံလောက်မှုအတွက် ဒဏ်ကြေး သင်သည်ပြန်လည်ပေးဆပ်ငွေကို ပေးသွင်းသော်လည်း သင့်ငွေစာရင်းထဲတွက် လက်ကျန်ငွေလုံလောက်စွာမရှိခြင်း သို့မဟုတ် သင့်ငွေစာရင်းကို စစ်ဆေး၍မရခြင်းတို့ဖြစ်ပေါ်ပါက ထိုပျက်ကွက်မှုအတွက် ၁၀,၀၀၀ကျပ်ကောက်ခံပါမည်။ ပျက်ကွက်ကြေးတစ်ကြိမ်ပေးသွင်းရပြီးနာက်ပိုင်းတွင် ပုံမှန်အတိုင်း လစဉ်ပေးဆပ်ရမည့်ငွေကို ဆက်လက်ပေးသွင်းသွားပါက သင့်ချေးငွေသည် ဆက်လက်အသက်ဝင်နေမည် ဖြစ်သော်လည်း ထိုပျက်ကွက်သောလအတွက်ငွေရင်း ပေးဆပ်မှုမှာလျော့နည်းသွားမည်ဖြစ်သည်။ ထို့ကြောင့် ကျန်ရှိသောလများအတွက် အတိုးပမာဏမှာ ပိုမိုလာနိုင်ပြီး နောက်ဆုံးပေးသွင်းရငွေမှာလည်း တိုးလာနိုင်ပါသည်။ သတ်မှတ်ရက်ထက်ပြက္ခဒိန်ရက် (၁၅)ရက်ထက်ကျော်လွန်ပြီး အပြည့်အဝပြန်လည်ပေးဆပ်ခြင်းမရှိပါက နောက်ကျကြေးပေးဆောင် ရမည် ဖြစ်ပါသည်။ အခကြေးငွေများနှင့် ပတ်သတ်၍ Mother Finance Mobile Application Platform ရှိ သင့်ငွေစာရင်းတွင် ထည့်သွင်းထားသောချေးငွေသဘောတူစာချုပ်တွင် အသေးစိတ်ဖတ်ရှုနိုင်ပါသည်။"

    [FAQs.F09]
        Question = "ချေးငွေလျောက်ထားရယူရန်အတွက် ငွေကြေးတစ်စုံတစ်ရာ ကျခံရန် လိုအပ်ပါသလား။"
        Answer = "ပဒေတာ မှ ချေးငွေရယူရန်အတွက် ငွေကြေးတစ်စုံတစ်ရာ စတင်ပေးချေရန် မလိုအပ်ပါ။ တစ်ကြိမ်သာပေးရသော ဝန်ဆောင်ခကို ချေးငွေထုတ်ပေးသည့်အခါ နှုတ်ယူထားမည် ဖြစ်ပါသည်။ စတင်ဆောင်ရွက်ခကို သင်ချေးယူသော ချေးငွေပမာဏ၏ ရာခိုင်နှုန်းဖြင့် တွက်ချက်ပါသည် (သင့်ပြန်လည်ပေးဆပ်နိုင်မှုပေါ်မူတည်၍ ၁% မှ ၅% ကြား ကျသင့်ပါမည်)။ ထိုဝန်ဆောင်ခကို သင့်ငွေစာရင်းသို့ ချေးငွေလွှဲပြောင်းခြင်းမပြုမီ နှုတ်ယူထားမည်ဖြစ်ပါသည်။ ထို့ကြောင့် တစ်စုံတစ်ခုဝယ်ယူရန် သို့မဟုတ် Credit card အတွက် ပြန်လည်ပေးဆပ်ရန် ချေးငွေလျောက်ထားပါက လိုအပ်သောငွေပမာဏအပြင် ဝန်ဆောင်ခကိုပါ ထည့်သွင်းစဉ်းစားရန် လိုအပ်ပါသည်။"

    [FAQs.F10]
        Question = "ချေးငွေအတွက်လိုအပ်သော စာရွက်စာတမ်းများကို မည့်သို့တင်ပြရပါမလဲ။"
        Answer = "ချေးငွေအတွက်လိုအပ်သော စာရွက်စာတမ်းများအားလုံးကို Mother Finance ၏ Mobile Application Platform မှတဆင့် တင်ပြနိုင်ပါသည်။ ဤနည်းလမ်းသည် လုံခြုံ စိတ်ချ မြန်ဆန်ပါသည်။"
        
    [FAQs.F11]
        Question = "ချေးငွေလျောက်ထားမှု အခြေအနေကို မည်သို့ သိရှိနိုင်ပါသလဲ။"
        Answer = "သင့်ချေးငွေလျောက်ထားမှု အခြေအနေကို Mother Finance Mobile Application Platform သို့ Login ဝင်ပြီး အချိန်မရွေး စစ်ဆေးနိုင်ပါသည်။ တင်ပြရန်ကျန်ရှိနေသေးသော စာရွက်စာတမ်းများကိုလဲ စစ်ဆေးသိရှိနိုင်ပြီး လျောက်ထားခြင်း ပြီးစီးမှုရာခိုင်နှုန်းကိုလဲ ဖော်ပြပေးထားပါသည်။"

    [FAQs.F12]
        Question = "ချေးငွေနှင့်ပတ်သတ်သည့် အသေးစိတ်အချက်လက်များကို ဘယ်မှာရှာလို့ ရပါသလဲ။"
        Answer = "ပဒေတာ Mobile Application Platform ကို Login ဝင်ပါ။  Mobile Application Platform ၏အောက်ခြေ တည်နေရာပြသည့်နေရာတွင် ရှိသည့်  “Account Overview”  icon ကို ဝင်ပါ။ သင့်ချေးငွေနှင့်ပတ်သတ်သည့် အသေးစိတ်အချက်အလက်များကို ကြည့်ရှုနိုင်ပါသည်။"

    [FAQs.F13]
        Question = "ချေးငွေလျောက်ထားမှု ဘာကြောင့် ပယ်ချခံရပါသလဲ။ ပယ်ချသည့်အခါ မည့်သည့်အချက်များကို ထည့်သွင်းစဉ်းစားပါသလဲ။"
        Answer = "ချေးငွေလျောက်ထားမှု ပယ်ချခံရခြင်းအတွက် စိတ်မကောင်းဖြစ်မိပါသည်။ ငွေပြန်လည်ပေးဆပ်နိုင်သည့် အလားအလာနည်းခြင်း သို့မဟုတ် ချေးငွေလျောက်လွှာနှင့်အတူ တင်ပြလာသော အချက်အလက်များ ထဲတွင် သေချာခိုင်မာမှုမရှိသော အချက်အလက်များပါဝင်နေခြင်းနေခြင်းတို့ကြောင့် ပယ်ချခံရခြင်း ဖြစ်နိုင် ပါသည်။ ကျွနု်ပ်တို့၏ ချေးငွေထုတ်ပေးရန် ဆုံးဖြတ်ခြင်းလုပ်ငန်းစဉ်သည် ချေးငွေသတင်းပေးပို့သော အဖွဲ့အစည်းများမှ သတ်မှတ်ထားသော ပိုင်ဆိုင်မှုများ စစ်ဆေးတိုင်းတာအကဲဖြတ်ခြင်း စံနှုန်းများပေါ်တွင် တည်ဆောက်ထားပါသည်။ တစ်နည်းအားဖြင့် သင်၏ ချေးငွေလျှောက်လွှာသည် Mother Finance မှသတ်မှတ်ထားသော လိုအပ်ချက်များနှင့် မပြည့်စုံသောကြောင့် (ဥပမာ - ယခင်လျှောက်လွှာကို ပယ်ချပြီး ရက်ပေါင်း ၁၂၀ မပြည့်ခင် ပြန်လည်လျှောက်ထားခြင်း သို့မဟုတ် လျှောက်ထားသူသည် အသက် ၁၈နှစ် မပြည့်သေးခြင်း) ဖြစ်နိုင်ပါသည်။"

    [FAQs.F14]
        Question = "ကနဦးခွင့်ပြုချက် ဆိုတာ ဘာလဲ။"
        Answer = "ကနဦးခွင့်ပြုချက်ဆိုသည်မှာ သင်သည် ချေးငွေအတွက် လိုအပ်သည့် ကနဦးစံနှုန်းများဖြင့် ပြည့်စုံသည်ဟု ဆိုလိုပါသည်။ ချေးငွေလျှောက်လွှာမတင်မီ သင့်အားပေးပို့ထားသည့် ကနဦးအချက်အလက်များဖြင့် တိုက်ဆိုင်စစ်ဆေးပြီး ကနဦးခွင့်ပြုချက် ရ/မရ ကို စစ်ဆေးသိရှိနိုင်ပါသည်။ ကနဦးခွင့်ပြုချက်သည် ချေးငွေချထားပေးရန် ခွင့်ပြုချက်မဟုတ်သောကြောင့် လိုအပ်သော စာရွက်စာတမ်းများကို Mother Finance Mobile Application Platform သို့ ပေးပို့လျှောက်ထားရန် လိုအပ်ပါသေးသည်။ Mother Finance မှ ထိုစာရွက်စာတမ်းများကို စစ်ဆေးပြီး သင်၏ ချေးငွေပြန်လည်ပေးဆပ်နိုင်မှု၊ ချေးငွေထုတ်ပေးရန်သင့်တော်မှုတို့ကို အကဲဖြတ်ပြီး ချေးငွေထုတ်ပေးရန် ဆုံးဖြတ်ပေးမည် ဖြစ်ပါသည်။"
        
    [FAQs.F15]
        Question = "ချေးငွေစည်းကမ်းချက်များကို ဘယ်မှာ ရှာလို့ရပါသလဲ။"
        Answer = "ငွေပေးချေရန်ကတိစာချုပ်တွင် ချေးငွေနှင့်ပတ်သတ်သော စည်းကမ်းချက်များပါဝင်ပါသည်။ ထို့ပြင် အသေး စိတ်အချက်အလက်များကို Mobile Application Platform ၏ Account Overview စာ မျက် နှာ တွင်လည်း ကြည့်ရှုနိုင်ပါသည်။"

    [FAQs.F16]
        Question = "ဘဏ်စာရင်းသို့အသားတင်ဝင်ရောက်လာမည့် ငွေမမာဏကို ဘယ်မှာသိရှိနိုင်ပါသလဲ။"
        Answer = "ငွေပေးချေရန်ကတိစာချူပ်ပါအတိုင်းချုပ်ဆိုထားသောအပြီးသတ်ငွေချေးသဘောတူစာချုပ်တွင် အမှန်တကယ်ထုတ်ချေးပေးသော ချေးငွေပမာဏနှင့် ပြန်လည်ပေးဆပ်ရန်အချိန်ဇယားတို့ကို ပါထည့်သွင်း ပေးထားပြီး ၎င်းကို Mobile Application Platform ၏ Account Overview စာမျက်နှာတွင် ကြည့်ရှုနိုင် ပါသည်။"

    [FAQs.F17]
        Question = "ချေးငွေစည်းကမ်းချက်များကို သဘောတူပြီးသည့်နောက် ဝင်ငွေ၊ အလုပ်အကိုင်နှင့်ပတ်သတ်သော အချက်အလက်များကို ပြင်ဆင်လိုပါက ဘယ်လိုပြင်ဆင်လို့ ရပါသလဲ။"
        Answer = "ချေးငွေစည်းကမ်းချက်များကို သဘောတူညီပြီးပါက ပြန်လည်ပြင်ဆင်လို့ မရနိုင်ပါ။ ယခင်ချေးငွေလျှောက်ထားမှုကို ချေးငွေမစတင်ခင် ပယ်ဖျက်ပြီး အသစ်ပြန်လည်လျှောက်ထားနိုင်ပါသည်။"

    [FAQs.F18]
        Question = "ချေးငွေကို မည်သည့်အချိန်တွင် ရရှိပါမလဲ။"
        Answer = "ချေးငွေထုတ်ပေးရန် အတည်ပြုသည့်နေ့တွင် သင်၏ဘဏ်စာရင်းထဲသို့ ပဒေတာ မှ ငွေလွှဲပြောင်းပေးမည် ဖြစ်ပါသည်။ ဘဏ်၏လုပ်ထုံးလုပ်နည်းပေါ်မူတည်၍ သင့်ဘဏ်စာရင်းထဲသို့ ငွေရောက်ရှိရန် အလုပ်ဖွင့်ရက် ၁ - ၃ ရက်အတွင်း ကြာမြင့်နိုင်ပါသည်။"
        
    [FAQs.F19]
        Question = "ချေးငွေပမာဏကို ပြောင်းလဲလို့ရနိုင်ပါသလား။"
        Answer = "ချေးငွေစည်းကမ်းချက်များကို သဘောတူညီပြီးပါက ပြန်လည်ပြင်ဆင်လို့ မရနိုင်ပါ။ ယခင်ချေးငွေလျှောက်ထားမှုကို ချေးငွေထုတ်ယူခွင့် မပြုမီနှင့်     ချေးငွေထုတ်ယူသုံးစွဲခြင်း မပြုမီ ပယ်ဖျက်ပြီး အသစ်ပြန်လည်လျှောက်ထားနိုင်ပါသည်။"
