[NotiPurchased]
    Title = "၀န်ဆောင်မှု ၀ယ်ယူပြီးပါပြီ"
    Description = "၀န်ဆောင်မှုကို အောင်မြင်စွာဝယ်ယူပြီးပါပြီ။ ဝန်ဆောင်ခ ၀.၃ ရာခိုင်နှုန်း ကောက်ခံလိုက်ပါပြီ။"
    
[NotiRank]
    Title = "အဆင့်တက်သွားပါပြီ။"
    Description = "ဂုဏ်ယူပါသည်။ သင့်ဂုဏ်သတင်းပြဇယားတွင် အဆင့်တက်သွားပါပြီ။ ပုံမှန်အတိုးနှုန်းပေးချေခြင်းဖြင့် ပရိုမိုးရှင်းနှင့်ဆုလက်ဆောင်များကို ရယူလိုက်ပါ။"

[NotiWarning]
    Title = "အတိုးနှုန်းပေးချေရန်"
    Description = "သင်ဝယ်ယူထားသော ဝန်ဆောင်မှုအတွက် အတိုးနှုန်းပေးချေရန်အချိန်နီးကပ်လာပြီဖြစ်သည်။ အချိန်မှီပေးခြင်းဖြင့် ဂုဏ်သတင်းပြဇယားတွင် အဆင့်တက်အောင်ကြိုးစားလိုက်ပါ။"
