[Packs]
    [Packs.P01]
        PackID = "P01"
        PackTitle = "စပါး လယ်ထွန်စက်"
        PackDescription = "ကျော်မိသားစုမှ လယ်သမားများအတွက် လယ်ထွန်စက်များကို အတိုးနှုန်းသက်သက်သာသာဖြင့် အရစ်ကျပေးချေပြီး ငှားရမ်း၊ရောင်းချ ပေးနေပါပြီ။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော လယ်ထွန်စက်အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ကျော်မိသားစု လယ်ထွန်စက်ရောင်းဝယ်ရေးကို ဖုန်းဆက်၍ စုံစမ်းမေးမြန်နိုင်ပါသည်။"
        PackAvailability = true
        PackPartner = "ကျော်မိသားစု လယ်ထွန်စက်ရောင်းဝယ်ရေး"
        PackImgURL = "https://cdn.pixabay.com/photo/2019/10/05/19/07/tractor-4528557_960_720.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၀၉ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P02]
        PackID = "P02"
        PackTitle = "လစဉ် ငွေတိုးချေးခြင်း"
        PackDescription = "GPS အသေးစားငွေချေးလုပ်ငန်းမှ တောင်သူလယ်သမားများအတွက် ငွေရေးကြေးရေး ဆိုင်ရာ အခက်အခဲများကို လိုလေသေးမရှိအောင် လစဉ် အတိုးနှုန်းသက်သက်သာသာဖြင့် ချေးပေး၍ ကူညီဆောင်ရွက်ပေးလျက်ရှိပါသည်။ ငွေတိုးနှုန်း နှင့် လစဉ် ချေးယူနိုင်သည့် ဝန်ဆောင်မှုအမျိုးမျိုးအား အသေးစိတ်သိရှိလိုပါက ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။ "
        PackAvailability = true
        PackPartner = "GPS အသေးစားငွေချေးလုပ်ငန်း"
        PackImgURL = "https://cdn.pixabay.com/photo/2014/09/12/18/57/burma-443189__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၀၉ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P03]
        PackID = "P03"
        PackTitle = "နှစ်စဥ် ငွေတိုးချေးခြင်း"
        PackDescription = "တောင်သူ အဆင့်မြင့်ငွေချေးလုပ်ငန်းမှ တောင်သူလယ်သမားများအတွက် ငွေရေးကြေးရေး ဆိုင်ရာ အခက်အခဲများကို လိုလေသေးမရှိအောင် နှစ်စဉ် အတိုးနှုန်းသက်သက်သာသာဖြင့် ချေးပေး၍ ကူညီဆောင်ရွက်ပေးလျက်ရှိပါသည်။ ငွေတိုးနှုန်း နှင့် နှစ်စဉ် ချေးယူနိုင်သည့် ဝန်ဆောင်မှုအမျိုးမျိုးအား အသေးစိတ်သိရှိလိုပါက ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။"
        PackAvailability = true
        PackPartner = "တောင်သူ အဆင့်မြင့်ငွေချေးလုပ်ငန်း"
        PackImgURL = "https://image.shutterstock.com/image-photo/table-takes-exchange-myanmar-money-600w-1502066420.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၀ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P04]
        PackID = "P04"
        PackTitle = "ကူဘိုတာ ရိပ်ခြွေ DC 70 G Plus"
        PackDescription = "DC- 70G ရဲ့ အားနည်းချက်တွေကို အခြေခံပြီး အဆင့်မြှင့်တင်ထားတဲ့ DC- 70G Plus တို့ရဲ့ ထူးခြားချက်တွေက… စပါးလှောင်ကန်က DC- 70G Plus မှာ ပိုမိုကျယ်ဝန်းလာခြင်း စက်အမြင့်မှာ DC- 70G Plus က အနည်းငယ် သာလွန်ခြင်း သီးနှံပြန်လည်ထုတ်ယူသည့် စနစ်တွင် DC- 70G Plus က လွန်သွားဖြင့် သယ်ယူပို့ဆောင်သည့်စနစ်ပါဝင်ခြင်း DC- 70G Plus ရှိ ရစ်လုံးတွင် ပိုက်လိုင်းထပ်ထည့်ပေးထားခြင်း DC- 70G Plus တွင် ခွေးသွားစိပ်ကို ပိုမိုကြီးထားသည့်အတွက် စပါးရိတ်ရာတွင် လည်ချောင်းချိန်းပြတ်ခြင်းနှင့် ဂီယာအံချော်ခြင်းကို လျော့ကျစေခြင်း DC- 70G ထက် ၁.၄ မှ ၂ ဆထိ ပိုမိုမာကြောလာခြင်း စပါးအထောင်အလှဲပေါ် မူတည်ပြီး ချိန်ညှိလို့ ရနိုင်ခြင်း တို့ ဖြစ်ပါတယ်။။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော ကူဘိုတာ ရိပ်ခြွေ DC 70 G အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။"
        PackAvailability = true
        PackPartner = "ရွှေလီ လယ်ယာသုံး စက်အပိုပစ္စည်းဆိုင်"
        PackImgURL = "https://cdn.pixabay.com/photo/2014/07/06/17/20/tractor-385681__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၀ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P05]
        PackID = "P05"
        PackTitle = "ပေါက်တူးပေါက်စက်(Mini Tiller)"
        PackDescription = "ရွှေလီ လယ်ယာသုံး စက်အပိုပစ္စည်းဆိုင်မှ တောင်သူလယ်သမားများအတွက် စပယ်ယာပစ်စည်းအမျိူးမျိူး အစရှိသော အပိုပစ္စည်းများ အပြင် အခြားအသစ်အသစ်သော စက်များကို အတိုးနှုန်းသက်သက်သာသာဖြင့် အရစ်ကျပေးချေပြီး ငှားရမ်း၊ရောင်းချ ပေးနေပါပြီ။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော ပေါက်တူးပေါက်စက်(Mini Tiller) အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။"
        PackAvailability = true
        PackPartner = "ရွှေလီ လယ်ယာသုံး စက်အပိုပစ္စည်းဆိုင်"
        PackImgURL = "https://image.shutterstock.com/image-photo/close-man-rotating-cultivating-tiller-600w-1083630164.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၁ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P06]
        PackID = "P06"
        PackTitle = "သစ်ဖြတ် လွှဝိုင်းခုံ 2 ပေ မှ 4 ပေထိ ထော်လီများ"
        PackDescription = "မြင်းကျား လယ်ယာသုံးစက်ပစ္စည်းဆိုင် မှ တောင်သူလယ်သမားများအတွက် စပယ်ယာပစ်စည်းအမျိူးမျိူး အစရှိသော အပိုပစ္စည်းများ အပြင် အခြားအသစ်အသစ်သော စက်များကို အတိုးနှုန်းသက်သက်သာသာဖြင့် အရစ်ကျပေးချေပြီး ငှားရမ်း၊ရောင်းချ ပေးနေပါပြီ။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော သစ်ဖြတ် လွှဝိုင်းခုံ 2 ပေ မှ 4 ပေထိ ထော်လီများ အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။"
        PackAvailability = true
        PackPartner = "မြင်းကျား လယ်ယာသုံးစက်ပစ္စည်းဆိုင်"
        PackImgURL = "https://image.shutterstock.com/image-photo/stump-grinder-action-600w-1044187762.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၁ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P07]
        PackID = "P07"
        PackTitle = "Air Compressor 2065 2080 2090"
        PackDescription = "မြင်းကျား လယ်ယာသုံးစက်ပစ္စည်းဆိုင် မှ တောင်သူလယ်သမားများအတွက် စပယ်ယာပစ်စည်းအမျိူးမျိူး အစရှိသော အပိုပစ္စည်းများ အပြင် အခြားအသစ်အသစ်သော စက်များကို အတိုးနှုန်းသက်သက်သာသာဖြင့် အရစ်ကျပေးချေပြီး ငှားရမ်း၊ရောင်းချ ပေးနေပါပြီ။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော Air Compressor 2065 2080 2090 အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။"
        PackAvailability = true
        PackPartner = "မြင်းကျား လယ်ယာသုံးစက်ပစ္စည်းဆိုင်"
        PackImgURL = "https://cdn.pixabay.com/photo/2015/07/11/12/17/compressor-840706__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၂ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P08]
        PackID = "P08"
        PackTitle = "ဓာတ်ဆီအင်ဂျင်မီးစက်များ"
        PackDescription = "ရွှေလီ လယ်ယာသုံး စက်အပိုပစ္စည်းဆိုင်မှ တောင်သူလယ်သမားများအတွက် စပယ်ယာပစ်စည်းအမျိူးမျိူး အစရှိသော အပိုပစ္စည်းများ အပြင် အခြားအသစ်အသစ်သော စက်များကို အတိုးနှုန်းသက်သက်သာသာဖြင့် အရစ်ကျပေးချေပြီး ငှားရမ်း၊ရောင်းချ ပေးနေပါပြီ။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော ဓာတ်ဆီအင်ဂျင်မီးစက်များ အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။"
        PackAvailability = true
        PackPartner = "ရွှေလီ လယ်ယာသုံး စက်အပိုပစ္စည်းဆိုင်"
        PackImgURL = "https://cdn.pixabay.com/photo/2015/08/08/06/39/machine-880144__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၂ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P09]
        PackID = "P09"
        PackTitle = "ငွေတိုးချေးခြင်း"
        PackDescription = "ရွက်လှေ ငွေချေးလုပ်ငန်း တောင်သူလယ်သမားများအတွက် ငွေရေးကြေးရေး ဆိုင်ရာ အခက်အခဲများကို လိုလေသေးမရှိအောင် အတိုးနှုန်းသက်သက်သာသာဖြင့် ချေးပေး၍ ကူညီဆောင်ရွက်ပေးလျက်ရှိပါသည်။ ငွေတိုးနှုန်း နှင့် ချေးယူနိုင်သည့် ဝန်ဆောင်မှုအမျိုးမျိုးအား အသေးစိတ်သိရှိလိုပါက ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။ "
        PackAvailability = true
        PackPartner = "ရွက်လှေ ငွေချေးလုပ်ငန်"
        PackImgURL = "https://image.shutterstock.com/image-photo/table-takes-exchange-myanmar-money-600w-1502066420.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၃ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P10]
        PackID = "P10"
        PackTitle = "KAWA ရိပ်ခြွေစက်အသေး (7.5H)"
        PackDescription = "ခွန်အား စက်ပစ္စည်းဆိုင်မှ တောင်သူလယ်သမားများအတွက် စပယ်ယာပစ်စည်းအမျိူးမျိူး အစရှိသော အပိုပစ္စည်းများ အပြင် အခြားအသစ်အသစ်သော စက်များကို အတိုးနှုန်းသက်သက်သာသာဖြင့် အရစ်ကျပေးချေပြီး ငှားရမ်း၊ရောင်းချ ပေးနေပါပြီ။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော ရိပ်ခြွေစက်အသေး အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။ "
        PackAvailability = true
        PackPartner = "ခွန်အား စက်ပစ္စည်းဆိုင်"
        PackImgURL = "https://image.shutterstock.com/image-photo/man-working-spring-garden-tiller-600w-1075475900.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၅ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P11]
        PackID = "P11"
        PackTitle = "နွားမကြီးမျိုး၆လ"
        PackDescription = "လိုချင်လာခဲ့ပါ ဧရာဝတီတိုင်းကျောင်းကုန်းမြို့နှင့်အနီးတဝိုက်ပဲလိုက်ပြပေးပါမယ် ရောင်းသူဝယ်သူ ဈေးစကားတည့်ပြော တည့်ဆစ် တတ်နိုင်လို့ အလကားပဲ ရရ ယူသွား နွားတစ်ကောင်တည့်ရင် ဝန်ဆောင်ခ 5 သောင်း‌တော့ကိုယ်ယူမယ် လက်ဘက်ရည်ဖိုးကွမ်းဖိုးလေးပေါ့ နွားပုံတွေနဲ့ တပ်ထားတဲ့ ဈေးနှုန်းလေးတွေ မရိုင်းဘူးလို့တော့ထင်ပါတယ် နီးစပ်သူတွေ လိုချင်ရင် ဆင်းခဲ့နော် ဈေးသင့်ထဲက ပုံရိုက်မထားတာ ဆယ်ကောင်လောက်ရှိသေးတယ်"
        PackAvailability = true
        PackPartner = "နွား၊ကျွဲ၊မြင်း၊ဝက်၊သိုး၊ဆိတ် မွေးမြူရေး ဝါသနာရှင်ရောင်းရင်းများ"
        PackImgURL = "https://cdn.pixabay.com/photo/2016/10/30/05/45/animals-1782431__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၆ အောက်တိုဘာ၊ ၂၀၁၉"

