[Packs]
    [Packs.P01]
        PackID = "P01"
        PackTitle = "အွန်လိုင်းချေးငွေ"
        PackDescription = "တောင်သူလယ်သမားများအနေဖြင့် ငွေရေးကြေးရေး အလျင်လိုအပ်နေပါသလား? ဒါပေမဲ့ ဘဏ်တွေမှာရော သင့်၏မိတ်ဆွေသူငယ်ချင်းများထံမှ ချေးယူရန်အခက်တွေ့နေပါသလား? Lendmoမှ သင့်ကိုကူညီပါရစေဗျာ"
        PackRnR = true
        PackPartner = "Lendmo Myanmar"
        PackImgURL = "https://cdn.pixabay.com/photo/2014/09/12/18/57/burma-443189__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၀၉ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P02]
        PackID = "P02"
        PackTitle = "လစဉ် ငွေတိုးချေးခြင်း"
        PackDescription = "GBS အသေးစားငွေချေးလုပ်ငန်းမှ တောင်သူလယ်သမားများအတွက် ငွေရေးကြေးရေး ဆိုင်ရာ အခက်အခဲများကို လိုလေသေးမရှိအောင် လစဉ် အတိုးနှုန်းသက်သက်သာသာဖြင့် ချေးပေး၍ ကူညီဆောင်ရွက်ပေးလျက်ရှိပါသည်။ ငွေတိုးနှုန်း နှင့် လစဉ် ချေးယူနိုင်သည့် ဝန်ဆောင်မှုအမျိုးမျိုးအား အသေးစိတ်သိရှိလိုပါက ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။ "
        PackRnR = true
        PackPartner = "GBS အသေးစားငွေချေးလုပ်ငန်း"
        PackImgURL = "https://cdn.pixabay.com/photo/2014/09/12/18/57/burma-443189__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၀၉ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P03]
        PackID = "P03"
        PackTitle = "နှစ်စဥ် ငွေတိုးချေးခြင်း"
        PackDescription = "အီရွန် Customer များ အဆင်ပြေလွယ်ကူစွာ ချေးငွေလျှောက်ထားနိုင်ရန်အတွက် AEON Microfinance (Myanmar) Co., Ltd. မှ S-Loan ချေးငွေများကို AEON Orange Hypermarket များတွင် လျှောက်ထားရယူနိုင်ပြီးဖြစ်ကြောင်း သတင်းကောင်းပါးအပ်ပါသည်။ AEON S-Loan ဝန်ဆောင်မှုအား လိုအပ်သောစာရွက်စာတမ်းများနှင့် အတူ အီရွန်ချေးငွေ ဝန်ဆောင်မှုရရှိသည့် နေရာများမှတဆင့်လျှောက်ထားနိုင်ပါတယ်။"
        PackRnR = true
        PackPartner = "AEON Microfinance Myanmar Co., Ltd."
        PackImgURL = "https://images.unsplash.com/photo-1495245495572-e43e6db5a478?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80"
        ContactNo = "09250030484"
        CreatedAt = "၁၀ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P04]
        PackID = "P04"
        PackTitle = "ကူဘိုတာ ရိပ်ခြွေ DC 70 G Plus"
        PackDescription = "DC- 70G ရဲ့ အားနည်းချက်တွေကို အခြေခံပြီး အဆင့်မြှင့်တင်ထားတဲ့ DC- 70G Plus တို့ရဲ့ ထူးခြားချက်တွေက… စပါးလှောင်ကန်က DC- 70G Plus မှာ ပိုမိုကျယ်ဝန်းလာခြင်း စက်အမြင့်မှာ DC- 70G Plus က အနည်းငယ် သာလွန်ခြင်း သီးနှံပြန်လည်ထုတ်ယူသည့် စနစ်တွင် DC- 70G Plus က လွန်သွားဖြင့် သယ်ယူပို့ဆောင်သည့်စနစ်ပါဝင်ခြင်း DC- 70G Plus ရှိ ရစ်လုံးတွင် ပိုက်လိုင်းထပ်ထည့်ပေးထားခြင်း DC- 70G Plus တွင် ခွေးသွားစိပ်ကို ပိုမိုကြီးထားသည့်အတွက် စပါးရိတ်ရာတွင် လည်ချောင်းချိန်းပြတ်ခြင်းနှင့် ဂီယာအံချော်ခြင်းကို လျော့ကျစေခြင်း DC- 70G ထက် ၁.၄ မှ ၂ ဆထိ ပိုမိုမာကြောလာခြင်း စပါးအထောင်အလှဲပေါ် မူတည်ပြီး ချိန်ညှိလို့ ရနိုင်ခြင်း တို့ ဖြစ်ပါတယ်။။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော ကူဘိုတာ ရိပ်ခြွေ DC 70 G အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။"
        PackRnR = true
        PackPartner = "ရွှေလီ လယ်ယာသုံး စက်အပိုပစ္စည်းဆိုင်"
        PackImgURL = "https://cdn.pixabay.com/photo/2014/07/06/17/20/tractor-385681__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၀ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P05]
        PackID = "P05"
        PackTitle = "ပေါက်တူးပေါက်စက်(Tiller)"
        PackDescription = "ရွှေလီ လယ်ယာသုံး စက်အပိုပစ္စည်းဆိုင်မှ တောင်သူလယ်သမားများအတွက် စပယ်ယာပစ်စည်းအမျိူးမျိူး အစရှိသော အပိုပစ္စည်းများ အပြင် အခြားအသစ်အသစ်သော စက်များကို အတိုးနှုန်းသက်သက်သာသာဖြင့် အရစ်ကျပေးချေပြီး ငှားရမ်း၊ရောင်းချ ပေးနေပါပြီ။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော ပေါက်တူးပေါက်စက်(Tiller) အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။"
        PackRnR = true
        PackPartner = "ရွှေလီ လယ်ယာသုံး စက်အပိုပစ္စည်းဆိုင်"
        PackImgURL = "https://cdn.pixabay.com/photo/2014/07/08/13/49/tractor-387275__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၁ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P06]
        PackID = "P06"
        PackTitle = "သစ်ဖြတ် လွှဝိုင်းခုံ 2 ပေ မှ 4 ပေထိ ထော်လီများ"
        PackDescription = "မြင်းကျား လယ်ယာသုံးစက်ပစ္စည်းဆိုင် မှ တောင်သူလယ်သမားများအတွက် စပယ်ယာပစ်စည်းအမျိူးမျိူး အစရှိသော အပိုပစ္စည်းများ အပြင် အခြားအသစ်အသစ်သော စက်များကို အတိုးနှုန်းသက်သက်သာသာဖြင့် အရစ်ကျပေးချေပြီး ငှားရမ်း၊ရောင်းချ ပေးနေပါပြီ။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော သစ်ဖြတ် လွှဝိုင်းခုံ 2 ပေ မှ 4 ပေထိ ထော်လီများ အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။"
        PackRnR = true
        PackPartner = "မြင်းကျား လယ်ယာသုံးစက်ပစ္စည်းဆိုင်"
        PackImgURL = "https://cdn.pixabay.com/photo/2015/10/20/14/55/motor-997841__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၁ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P07]
        PackID = "P07"
        PackTitle = "(လေမှုတ်စက်)Air Compressor 2065 2080 2090"
        PackDescription = "မြန်မာမဟာထွန်း မှ တောင်သူလယ်သမားများအတွက် စပယ်ယာပစ်စည်းအမျိူးမျိူး အစရှိသော အပိုပစ္စည်းများ အပြင် အခြားအသစ်အသစ်သော စက်များကို အတိုးနှုန်းသက်သက်သာသာဖြင့် အရစ်ကျပေးချေပြီး ငှားရမ်း၊ရောင်းချ ပေးနေပါပြီ။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော Air Compressor 2065 2080 2090 အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။"
        PackRnR = true
        PackPartner = "မြန်မာမဟာထွန်း"
        PackImgURL = "https://cdn.pixabay.com/photo/2015/07/11/12/17/compressor-840706__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၂ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P08]
        PackID = "P08"
        PackTitle = "ဓာတ်ဆီအင်ဂျင်မီးစက်များ"
        PackDescription = "ရွှေလီ လယ်ယာသုံး စက်အပိုပစ္စည်းဆိုင်မှ တောင်သူလယ်သမားများအတွက် စပယ်ယာပစ်စည်းအမျိူးမျိူး အစရှိသော အပိုပစ္စည်းများ အပြင် အခြားအသစ်အသစ်သော စက်များကို အတိုးနှုန်းသက်သက်သာသာဖြင့် အရစ်ကျပေးချေပြီး ငှားရမ်း၊ရောင်းချ ပေးနေပါပြီ။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော ဓာတ်ဆီအင်ဂျင်မီးစက်များ အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။"
        PackRnR = true
        PackPartner = "ရွှေလီ လယ်ယာသုံး စက်အပိုပစ္စည်းဆိုင်"
        PackImgURL = "https://cdn.pixabay.com/photo/2015/08/08/06/39/machine-880144__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၂ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P09]
        PackID = "P09"
        PackTitle = "ငွေတိုးချေးခြင်း"
        PackDescription = "တိုးတက်ပြောင်းလဲနေတဲ့ခေတ်မှာ မိတ်ဆွေတို့ရဲ့ လုပ်ငန်းကို ကြီးထွားတိုးတက် ခေတ်မီအောင် တိုးချဲ့သင့်ပြီနော်။ တောင်သူလယ်သမားများအတွက် အရေးပေါ်ငွေးရေးကြေးရေး အခက်အခဲများအတွက် AYA SME Loan ဖြစ်တဲ့ Shop Owner Loan ဝန်ဆောင်မှုကို လျောက်ထားနိုင်ပါတယ်။ "
        PackRnR = true
        PackPartner = "ဧရာ၀တီဘဏ်"
        PackImgURL = "https://images.unsplash.com/photo-1495245495572-e43e6db5a478?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80"
        ContactNo = "09250030484"
        CreatedAt = "၁၃ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P10]
        PackID = "P10"
        PackTitle = "KAWA ရိပ်ခြွေစက်အသေး (7.5H)"
        PackDescription = "ခွန်အား စက်ပစ္စည်းဆိုင်မှ တောင်သူလယ်သမားများအတွက် စပယ်ယာပစ်စည်းအမျိူးမျိူး အစရှိသော အပိုပစ္စည်းများ အပြင် အခြားအသစ်အသစ်သော စက်များကို အတိုးနှုန်းသက်သက်သာသာဖြင့် အရစ်ကျပေးချေပြီး ငှားရမ်း၊ရောင်းချ ပေးနေပါပြီ။ ပုံတွင်ပြထားသည့် သိပ်မကြာသေးခင်မှ အသစ်ရောက်ရှိသော ရိပ်ခြွေစက်အသေး အား ငှားရမ်းလိုသည်ဖြစ်စေ ဝယ်ယူလိုသည်ဖြစ်စေ ဖော်ပြပါဖုန်နံပါတ်အား ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။ "
        PackRnR = true
        PackPartner = "ခွန်အား စက်ပစ္စည်းဆိုင်"
        PackImgURL = "https://cdn.pixabay.com/photo/2015/04/06/11/17/tiller-709117__340.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၁၅ အောက်တိုဘာ၊ ၂၀၁၉"

    [Packs.P12]
        PackID = "P01"
        PackTitle = "Yanmar EF514T ထွန်စက်"
        PackDescription = "လယ်ကွင်းထဲမှာပဲဖြစ်ဖြစ် ခက်ခဲကြမ်းတမ်းသော မြေအမျိုးအစားမှာပဲဖြစ်ဖြစ် နေရာဒေသ မရွေးအသုံးပြုနိုင်ေသော မြင်းကောင် ရေ (၅၁) ကောင်အားရှိသည့်ဒီဇယ်အင်ဂျင်ကိုသာ အသုံးပြုလိုက်ပါလွယ်ကူလျင်မြန်စွာ ထွန်ယက်စိုက်ပျိုးနို င်လို့လူကြီးမင်းတို့ ဝင်ငွေ ပိုတိုးစေနိုင်ပါသည်။အကြမ်းခံသော ထရန်စမစ်ရှင်း ကို အသုံးပြုထားသောကြောင့် လုပ်ငန်းပြီးမြောက်မှု ပိုမိုတွင်ကျယ်ပြီး၊ စွမ်းဆောင်ရည်အပြည့်အဝဖြင့် ပြုပြင်ထိန်းသိမ်းမှုကုန်ကျစရိတ်နည်းပါး စွာအသုံးပြုနိုင်ပါသည်။"
        PackRnR = true
        PackPartner = "Yanmar Myanmar"
        PackImgURL = "https://cdn.pixabay.com/photo/2019/10/05/19/07/tractor-4528557_960_720.jpg"
        ContactNo = "09250030484"
        CreatedAt = "၀၉ အောက်တိုဘာ၊ ၂၀၁၉"

